name: Build Executables

on:
  push:
    branches:
      - main
      - feature/ci_cd
    tags:
      - "v*.*.*"
  pull_request:
    braches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-apple-darwin,
            x86_64-pc-windows-msvc,
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Executables
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Executables
          path: |
            target/${{ matrix.target }}/release/media_tools*
          if-no-files-found: error
